### PR TITLE
Make docs more accessible

### PR DESCRIPTION
**Pull request by staeff**
I checked out your repo and found the docs not as easy to access. I added [MkDocs](https://www.mkdocs.org/) to the repo, which allows to easily generate a nice looking, searchable documentation of the existing doc files in `docs`.

I added a command to live serve (`make serve_docs`) and build (`make build_docs`).

I made some minor formal fixes on the existing doc files.

### CODE REVIEW

**Comment by pbanaszkiewicz** [comment]
@fmichonneau we could use this opportunity to start hosting the docs on either Github Pages or Read The Docs.

@staeff I will review the changes soon.

**Review by pbanaszkiewicz — CHANGES_REQUESTED** [review]
@staeff thank you for the contribution. In general this is looking well. I'd like to see one small change: the link to "Template hierarchy" from menu is 404.

**Comment by staeff** [comment]
@pbanaszkiewicz thank you for the review and for spotting the wrong link to "Template hierarchy". I fixed it.

**Comment by fmichonneau** [comment]
@pbanaszkiewicz I'd be happy to set up GitHub Actions to build and deploy the docs on the gh-pages branch for using GitHub pages hosting.

**Review by pbanaszkiewicz — APPROVED** [review]

**Comment by pbanaszkiewicz** [comment]
@staeff thank you for your contribution!

@fmichonneau thanks! I can see there are some actions for mkdocs in the marketplace, but I think we can write our own CI yaml: https://squidfunk.github.io/mkdocs-material/publishing-your-site/
We can discuss this on Friday.

**Pull request merged**
