### PR TITLE
Miscellaneous changes to the workshop request/inquiry/submission forms

### PR DESCRIPTION
**Pull request by maneesha**
Based on conversations with @sheraaronhurt  and the Workshop Admin team, this PR makes a few changes to the forms to make them more consistent with the AMY event and with our workflows.

This includes:

* Changing references to "Workshop type" to "Curricula"
* Referring to "Host Contact" rather than "Person"
* Making label for "Contact" field verbose and more informative

@sheraaronhurt  screenshots of what all the views look like now are below.  Please verify that this is what you are looking for before @pbanaszkiewicz  works on merging them.  

**NOTE**: All names are fake data and do not represent real persons or institutions.

### CODE REVIEW

**Comment by maneesha** [comment]
### Changes to the workshop request view

image

**Comment by maneesha** [comment]
### Changes to the self organized submission view

image

**Comment by maneesha** [comment]
### Changes to the Inquiry submission view 

image

**Comment by maneesha** [comment]
### Change in the Event view

image

**Comment by sheraaronhurt** [comment]
@maneesha this captures everything we discussed. Thanks!

**Pull request merged**
