### PR TITLE
Improve performance with advanced statics caching

### PR DESCRIPTION
**Pull request by pbanaszkiewicz**
This replaces django-compressor with whitenoise - a WSGI middleware
which handles caching, compression, etc. of static files.

### CODE REVIEW

**Comment by pbanaszkiewicz** [comment]
There's a couple of issues with this PR.

1. whitenoise setup/teardown during WSGI application setup/weardown is painfully slow, and hence it slows down testing by a lot.
2. `node_modules` contains sources for JS/CSS packages we're dependent on, but the whole directory is set as static source (`STATICFILES_DIRS` setting). This slows down the setup and `./manage.py collectstatic`, and has high impact on testing as well.
3. there are some unused dependencies (to be fixed with next commit).

All in all, here's related issue: https://github.com/evansd/whitenoise/issues/94
And here's related documentation: http://whitenoise.evans.io/en/stable/django.html#whitenoise-makes-my-tests-run-slow

It also looks like we should switch to JS development with webpack to shear off files ending up in `staticfiles` directory.

**Comment by pbanaszkiewicz** [comment]
Ref #1875

**Comment by lauryndbrown** [comment]
@pbanaszkiewicz are you wanting my review on this one?

**Comment by pbanaszkiewicz** [comment]
@lauryndbrown no, I don't want you to review this; it's not ready yet and frankly quite some work needs to be done.

**Comment by pbanaszkiewicz** [comment]
I think I have a better solution.

**Pull request closed without merging**
