### PR TITLE
main: Fix server error on organizations membership

### LINKED ISSUE #2313: Bug: Internal Server Error: /fiscal/organizations/
Production issue.

```
FieldError at /fiscal/organizations/
Cannot resolve keyword 'membership' into field. Choices are: administered_events, affiliated_organizations, country, domain, fullname, hosted_events, id, latitude, longitude, member, memberships, selforganisedsubmission, sponsored_events, workshopinquiryrequest, workshoprequest
```

https://amy.carpentries.org/fiscal/organizations/?country=&membership__variant=silver&order_by=

### PR DESCRIPTION
**Pull request by elichad**
Fixes #2313.

### CODE REVIEW

**Review by pbanaszkiewicz — APPROVED** [review]

**Comment by pbanaszkiewicz** [comment]
@maneesha Do you want this fix sooner in production, or is 4.1 release okay?

**Comment by maneesha** [comment]
What is the timeline for 4.1 release? If it's not too long (like in the next week) I'm fine waiting.  Otherwise we should push this through.

**Comment by pbanaszkiewicz** [comment]
@maneesha We didn't decide on v4.1 just yet. I can move @elichad's fix to prod via a release branch during this weekend, does that sound good to you?

**Comment by pbanaszkiewicz** [comment]
I'm going to release this code change by cherry-picking from `develop` into a `release/v4.0.7` branch.

**Pull request closed without merging**
