### PR TITLE
Admin dashboard: change conditions and calculations in "Current events", "Unpublished events" columns

### LINKED ISSUE #1516: Update "published" requirements
In addition to current requirements, a workshop should not show in the "Current" column in the AMY dashboard until at least one instructor has been assigned.

### LINKED ISSUE #1716: Include Supporting Instructors in count in  "Unpublished workshops" table
The dashboard view shows "Unpublished workshops" with a column for number of Instructors.
This number should be the sum total of Instructors and Supporting Instructors (not two separate columns).

image

### PR DESCRIPTION
**Pull request by pbanaszkiewicz**
This fixes #1716.

WIP. TODO: fix #1516 once clarification provided.

### CODE REVIEW

**Review by fmichonneau — APPROVED** [review]

**Comment by fmichonneau** [comment]
this looks good to me but I'm wondering whether @carpentries/core-team-workshop-admin would prefer to see a separate count for instructors and supporting instructors?

**Comment by Talishask** [comment]
Based on our notes at the time, No. It looks like we were hoping to see the total # of instructors and did not need a breakdown. Here are the meeting notes: 

> AMY dashboard Unpublished … not included in the number of instructors
- Could we include the # of supporting instructors in the total number of instructors? We don’t need to see the breakdown of instructors versus supporting instructors. I.e. 2 instructors + 2 supporting instructors = 4 instructors for the workshop being listed on the table

**Comment by maneesha** [comment]
Yes, as noted in #1716

> This number should be the sum total of Instructors and Supporting Instructors (not two separate columns).

**Comment by pbanaszkiewicz** [comment]
@Talishask @maneesha 
Thank you for your answers. I need further clarification regarding #1516, here's my question: https://github.com/carpentries/amy/issues/1516#issuecomment-725578501

**Comment by pbanaszkiewicz** [comment]
@maneesha @Talishask @sheraaronhurt please take a minute to answer my question mentioned in the above comment (https://github.com/carpentries/amy/pull/1747#issuecomment-726370283)

**Pull request closed without merging**
