### PR TITLE
Display person consents when merging

### LINKED ISSUE #2370: Display consents in person merge view
When merging two Persons, their consents don't display correctly in the merge view (but are still merged). We could copy what has been written for the training requests merge view: 
https://github.com/carpentries/amy/pull/2363/files#diff-28b075b2b3e469ffbc4023daeb7f657ce17236f815f3aebfe1f64c8783d2d60cR955
https://github.com/carpentries/amy/pull/2363/files#diff-db895696b527b478871dcb468a1b1d3a896d565667ab30f6e1cf1a9150c18783R234

### PR DESCRIPTION
**Pull request by pbanaszkiewicz**
This fixes #2370.

### CODE REVIEW

**Comment by pbanaszkiewicz** [comment]
@elichad sure. I will work on this later this week.

**Comment by elichad** [comment]
Great, thanks.
Another idea that came out of the discussion was that we could send an email to the merged person, letting them know that their records have been merged and that they should check everything is okay (consents and the rest of their info). I'll make a separate issue for that as I think it fits better into the email automation project.

**Comment by pbanaszkiewicz** [comment]
This is WIP and may require updated tests.

**Comment by pbanaszkiewicz** [comment]
@elichad Ready for your re-review.

**Pull request merged**
