### PR TITLE
[#2098] Change Fee Choices for request and inquiry forms

### LINKED ISSUE #2098: Update pricing information in AMY
Currently we have mentions of The Carpentries workshop fee of $2500 on our [request](https://github.com/carpentries/amy/blob/develop/amy/workshops/models.py#L2976) and [inquiry](https://github.com/carpentries/amy/blob/develop/amy/extrequests/models.py#L249) forms.  

> I am with a government site, university, or other nonprofit. I understand the workshop fee of US$2500, and agree to follow through on The Carpentries invoicing process.

This text should be changed to 

> I am with a government site, university, or other nonprofit. I understand the workshop fee as listed on [The Carpentries website](https://carpentries.org/workshops/#workshop-cost) and agree to follow through on The Carpentries invoicing process.

This change should take effect anytime before January 4, 2022.  ~~I will update the link to the website shortly.~~ 

EDIT to link to the workshop cost page and update timeline.

### PR DESCRIPTION
**Pull request by pbanaszkiewicz**
Fixes #2098

### CODE REVIEW

**Comment by pbanaszkiewicz** [comment]
@maneesha I need URL for the destination page.

I also have small issue with the link. This is the default way Django renders the changed choice text:
obraz

As you can see, `<a href>` is rendered literally, so I was wondering if you're okay with putting this link into help text instead of the choice option. If it was there, the HTML rendering would work just fine.

If you prefer to keep the link inside choice option, then I will spend some time figuring out how to do it.

**Comment by maneesha** [comment]
I will share the url shortly.
It's fine to have it in the help text.

**Comment by pbanaszkiewicz** [comment]
@maneesha the help text version would look like this:
obraz

Please correct my verbiage.

**Comment by pbanaszkiewicz** [comment]
@maneesha I changed the options. Here's how it looks like now.

Workshop Inquiry:
obraz
(Removed "Not sure yet", changed options for "for-profit", "member" and waiver).

Workshop Request:
obraz
(Changed options for "for-profit", "member" and waiver).

@maneesha please remember about the link for destination page.

**Comment by pbanaszkiewicz** [comment]
I found the link: https://carpentries.org/workshops/#workshop-cost

**Pull request merged**
