### PR TITLE
[#1834] Organisation coordinates

### LINKED ISSUE #1834: Organisation: add latitude, longitude
Organisation should be extended with geographical information (lat/long similarly to events).

### PR DESCRIPTION
**Pull request by pbanaszkiewicz**
This fixes #1834.

The PR currently contains changes from previous PR #1837.

### CODE REVIEW

**Comment by lauryndbrown** [comment]
It's a little hard to review with the changed from #1837. I reviewed that one, could you at mention me again when that one gets merged? I'll review this one after.

**Comment by pbanaszkiewicz** [comment]
@lauryndbrown this PR has been rebased and should be now much clearer for your review.

**Review by lauryndbrown — APPROVED** [review]
Looks good!

**Comment by lauryndbrown** [comment]
Oh one thing I forgot to note: I noticed that the organization's fields are mentioned in the docs: https://github.com/carpentries/amy/blob/develop/docs/amy_database_structure.md#organizations

Not sure if you wanted to add lat and long to those as well.

**Pull request merged**
