### PR TITLE
Update text for conflicting workshops at instructor sign-up

### LINKED ISSUE #2256: Update text if instructor tries to sign up for conflicting workshop
Right now, if an instructor tries to sign up for conflicting workshop, they get this error message:

> You cannot apply for this workshop. You are teaching at a conflicting workshop: <slug>

The following text should be added to this error message:

> If you are still interested in teaching at this workshop, please contact workshops@carpentries.org.

### PR DESCRIPTION
**Pull request by elichad**
Fixes #2256

### CODE REVIEW

**Review by pbanaszkiewicz — APPROVED** [review]

**Comment by elichad** [comment]
@pbanaszkiewicz what do you mean by assigning me here? I haven't used this field in the past

**Comment by pbanaszkiewicz** [comment]
> @pbanaszkiewicz what do you mean by assigning me here? I haven't used this field in the past

I usually keep PR's author as `Assignee`, and all reviewers as `Reviewers`. Do you have a better idea how can we use `Reviewers` field?

**Comment by elichad** [comment]
No, that's fine with me. Who's responsible for merging after approval?

**Comment by pbanaszkiewicz** [comment]
If you have approval, then go ahead and merge except for #2321. I'm still waiting for @maneesha's answer in https://github.com/carpentries/amy/pull/2321#issuecomment-1404042908. Plus I think if you merge change #2324 then we can use cherry-pick to move it to production via a release branch (hopefully this will prevent conflicts when we merge `develop` into `main` at some point in future).

**Comment by elichad** [comment]
Ok, thanks

**Pull request merged**
