### PR TITLE
fix(Consents): Fixed issue with admin term and term option add being broken.

### PR DESCRIPTION
**Pull request by lauryndbrown**
Fixes https://github.com/carpentries/amy/issues/1909

### CODE REVIEW

**Comment by lauryndbrown** [comment]
Add terms page:

Screen Shot 2021-04-24 at 4 30 13 PM

Add term options page:
Screen Shot 2021-04-24 at 4 31 14 PM

Consents were changed to view only
Screen Shot 2021-04-24 at 4 32 28 PM

**Comment by lauryndbrown** [comment]
cc @fmichonneau

**Comment by lauryndbrown** [comment]
todo: doubled check creating a required term works ok and doesn't lock the admin out immediately. Maybe force it to be optional on creation and the admin has to change it to required

**Review by pbanaszkiewicz — APPROVED** [review]

**Comment by lauryndbrown** [comment]
Screen Shot 2021-04-26 at 10 41 22 AM
Screen Shot 2021-04-26 at 10 50 23 AM
Screen Shot 2021-04-26 at 10 51 40 AM

**Pull request merged**
